# Generated by Django 2.2.8 on 2020-02-13 15:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skipper_dataseries_storage_dynamic_sql', '0006_add_record_source_and_user_id'),
    ]

    replaces = [
        ('skipper.dataseries.storage.dynamic_sql', '0007_datapoint_datapoint_dimension_datapoint_floatfact_datapoint_imagefact_datapoint_jsonfact_datapoint_s')
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('data_series_id', models.UUIDField()),
                ('external_id', models.CharField(default=None, max_length=256)),
                ('deleted', models.BooleanField(default=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
            ],
            options={
                'db_table': '_3_view_data_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataPoint_Dimension',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('dimension_id', models.UUIDField()),
                ('value', models.CharField(default=None, max_length=512)),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
            ],
            options={
                'db_table': '_3_view_data_point_dimension',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataPoint_FloatFact',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
                ('fact_id', models.UUIDField()),
                ('value', models.FloatField(null=True)),
            ],
            options={
                'db_table': '_3_view_data_point_float_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataPoint_ImageFact',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
                ('fact_id', models.UUIDField()),
                ('value', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': '_3_view_data_point_image_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataPoint_JsonFact',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
                ('fact_id', models.UUIDField()),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
            ],
            options={
                'db_table': '_3_view_data_point_json_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataPoint_StringFact',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
                ('fact_id', models.UUIDField()),
                ('value', models.CharField(default=None, max_length=256, null=True)),
            ],
            options={
                'db_table': '_3_view_data_point_string_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataPoint_TextFact',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
                ('fact_id', models.UUIDField()),
                ('value', models.TextField(null=True)),
            ],
            options={
                'db_table': '_3_view_data_point_text_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataPoint_TimestampFact',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
                ('fact_id', models.UUIDField()),
                ('value', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': '_3_view_data_point_timestamp_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisplayDataPoint',
            fields=[
                ('id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('external_id', models.CharField(default=None, max_length=256)),
                ('current_version', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('versions', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
            ],
            options={
                'db_table': 'DOES_NOT_EXIST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WritableDataPoint',
            fields=[
                ('id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('data_series_id', models.UUIDField()),
                ('external_id', models.CharField(default=None, max_length=256)),
                ('deleted', models.BooleanField(default=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
            ],
            options={
                'db_table': '_3_data_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WritableDataPoint_Dimension',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('dimension_id', models.UUIDField()),
                ('value', models.CharField(default=None, max_length=512)),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
            ],
            options={
                'db_table': '_3_data_point_dimension',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WritableDataPoint_FloatFact',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
                ('fact_id', models.UUIDField()),
                ('value', models.FloatField(null=True)),
            ],
            options={
                'db_table': '_3_data_point_float_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WritableDataPoint_ImageFact',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
                ('fact_id', models.UUIDField()),
                ('value', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': '_3_data_point_image_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WritableDataPoint_JsonFact',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
                ('fact_id', models.UUIDField()),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
            ],
            options={
                'db_table': '_3_data_point_json_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WritableDataPoint_StringFact',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
                ('fact_id', models.UUIDField()),
                ('value', models.CharField(default=None, max_length=256, null=True)),
            ],
            options={
                'db_table': '_3_data_point_string_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WritableDataPoint_TextFact',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
                ('fact_id', models.UUIDField()),
                ('value', models.TextField(null=True)),
            ],
            options={
                'db_table': '_3_data_point_text_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WritableDataPoint_TimestampFact',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
                ('fact_id', models.UUIDField()),
                ('value', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': '_3_data_point_timestamp_fact',
                'managed': False,
            },
        ),
    ]
