# Generated by Django 2.2.8 on 2020-03-06 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skipper_dataseries_storage_dynamic_sql', '0007_datapoint_datapoint_dimension_datapoint_floatfact_datapoint_imagefact_datapoint_jsonfact_datapoint_s'),
    ]

    replaces = [
        ('skipper.dataseries.storage.dynamic_sql', '0008_auto_20200306_2008')
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'default_permissions': [], 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='displaydatapoint',
            options={'default_permissions': [], 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='writabledatapoint',
            options={'default_permissions': [], 'managed': False},
        ),
    ]
