# Generated by Django 2.2.8 on 2020-03-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skipper_dataseries_storage_dynamic_sql', '0008_auto_20200306_2008'),
    ]

    replaces = [
        ('skipper.dataseries.storage.dynamic_sql', '0009_auto_20200306_2011')
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint_dimension',
            options={'default_permissions': [], 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='datapoint_floatfact',
            options={'default_permissions': [], 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='datapoint_imagefact',
            options={'default_permissions': [], 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='datapoint_jsonfact',
            options={'default_permissions': [], 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='datapoint_stringfact',
            options={'default_permissions': [], 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='datapoint_textfact',
            options={'default_permissions': [], 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='datapoint_timestampfact',
            options={'default_permissions': [], 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='writabledatapoint_dimension',
            options={'default_permissions': [], 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='writabledatapoint_floatfact',
            options={'default_permissions': [], 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='writabledatapoint_imagefact',
            options={'default_permissions': [], 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='writabledatapoint_jsonfact',
            options={'default_permissions': [], 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='writabledatapoint_stringfact',
            options={'default_permissions': [], 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='writabledatapoint_textfact',
            options={'default_permissions': [], 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='writabledatapoint_timestampfact',
            options={'default_permissions': [], 'managed': False},
        ),
    ]
