# Generated by Django 2.2.8 on 2020-04-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skipper_dataseries_storage_dynamic_sql', '0009_auto_20200306_2011'),
    ]

    replaces = [
        ('skipper.dataseries.storage.dynamic_sql', '0010_datapoint_booleanfact_writabledatapoint_booleanfact')
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint_BooleanFact',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
                ('fact_id', models.UUIDField()),
                ('value', models.BooleanField(null=True)),
            ],
            options={
                'db_table': '_3_view_data_point_boolean_fact',
                'managed': False,
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='WritableDataPoint_BooleanFact',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
                ('fact_id', models.UUIDField()),
                ('value', models.BooleanField(null=True)),
            ],
            options={
                'db_table': '_3_data_point_boolean_fact',
                'managed': False,
                'default_permissions': [],
            },
        ),
    ]
