# Generated by Django 3.0.7 on 2020-06-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skipper_dataseries_storage_dynamic_sql', '0011_boolean_fact_custom'),
    ]

    replaces = [
        ('skipper.dataseries.storage.dynamic_sql', '0012_datapoint_filefact_writabledatapoint_filefact')
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint_FileFact',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
                ('fact_id', models.UUIDField()),
                ('value', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': '_3_view_data_point_file_fact',
                'managed': False,
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='WritableDataPoint_FileFact',
            fields=[
                ('data_point_id', models.CharField(default=None, max_length=512, primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField()),
                ('user_id', models.CharField(default=None, max_length=512, null=True)),
                ('record_source', models.CharField(default=None, max_length=512, null=True)),
                ('fact_id', models.UUIDField()),
                ('value', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': '_3_data_point_file_fact',
                'managed': False,
                'default_permissions': [],
            },
        ),
    ]
