# Generated by Django 4.1.7 on 2023-02-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skipper_dataseries_storage_dynamic_sql', '0025_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisplayDataPoint',
        ),
    ]
