# Generated by Django 4.1.9 on 2023-05-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skipper_dataseries_storage_dynamic_sql', '0026_delete_displaydatapoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPoint_BooleanFact',
        ),
        migrations.DeleteModel(
            name='DataPoint_Dimension',
        ),
        migrations.DeleteModel(
            name='DataPoint_FileFact',
        ),
        migrations.DeleteModel(
            name='DataPoint_FloatFact',
        ),
        migrations.DeleteModel(
            name='DataPoint_ImageFact',
        ),
        migrations.DeleteModel(
            name='DataPoint_JsonFact',
        ),
        migrations.DeleteModel(
            name='DataPoint_StringFact',
        ),
        migrations.DeleteModel(
            name='DataPoint_TextFact',
        ),
        migrations.DeleteModel(
            name='DataPoint_TimestampFact',
        ),
        migrations.DeleteModel(
            name='WritableDataPoint_BooleanFact',
        ),
        migrations.DeleteModel(
            name='WritableDataPoint_Dimension',
        ),
        migrations.DeleteModel(
            name='WritableDataPoint_FileFact',
        ),
        migrations.DeleteModel(
            name='WritableDataPoint_FloatFact',
        ),
        migrations.DeleteModel(
            name='WritableDataPoint_ImageFact',
        ),
        migrations.DeleteModel(
            name='WritableDataPoint_JsonFact',
        ),
        migrations.DeleteModel(
            name='WritableDataPoint_StringFact',
        ),
        migrations.DeleteModel(
            name='WritableDataPoint_TextFact',
        ),
        migrations.DeleteModel(
            name='WritableDataPoint_TimestampFact',
        ),
    ]
