# Generated by Django 4.1.9 on 2023-05-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skipper_dataseries_storage_dynamic_sql', '0027_delete_datapoint_booleanfact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WritableDataPoint',
        ),
    ]
