# Generated by Django 2.2.8 on 2020-05-08 22:26

from django.db import migrations, models
from typing import List, Any


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Any] = []

    operations = [
        migrations.CreateModel(
            name='FlowPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('edit', 'Allowed to edit flows'), ('impl', 'Allowed to access flow implementation endpoints')),
                'managed': False,
                'default_permissions': [],
            },
        ),
    ]
