# Generated by Django 3.0.7 on 2020-06-11 12:55

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_multitenant.mixins  # type: ignore
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200611_1255'),
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regex', models.BooleanField()),
                ('path', models.CharField(max_length=256)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Tenant')),
            ],
            options={
                'db_table': '_flow_flow',
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
