# Generated by Django 3.0.7 on 2020-06-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_flow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flow',
            table='_4_flow',
        ),
    ]
