# Generated by Django 3.0.7 on 2020-06-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_auto_20200612_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='regex',
        ),
    ]
