# Generated by Django 3.0.7 on 2020-06-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_remove_flow_regex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flow',
            options={'permissions': (('use', 'Allowed to use endpoint'),)},
        ),
    ]
