# Generated by Django 3.0.7 on 2020-07-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_auto_20200612_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10),
        ),
    ]
