# Generated by Django 3.0.9 on 2020-09-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0007_auto_20200925_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
