# Generated by Django 3.1.2 on 2020-12-17 13:38

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.mixins  # type: ignore
import skipper.core.models.softdelete
import skipper.core.models.validation
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_tasklogentry'),
        ('flow', '0010_auto_20201216_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=256, validators=[skipper.core.models.validation.external_id_validator_sql_safe])),
                ('upstream', models.CharField(max_length=256)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tenant')),
            ],
            options={
                'db_table': '_4_engine',
                'default_permissions': []
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.core.models.softdelete.SoftDeletionTenantManager()),
            ],
        ),
    ]
