# Generated by Django 3.1.2 on 2020-12-17 13:59

from django.db import migrations, models
import skipper.flow.models.http_endpoint


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0011_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='upstream',
            field=models.URLField(max_length=256),
        ),
        migrations.AlterField(
            model_name='flow',
            name='path',
            field=models.CharField(max_length=256, validators=[skipper.flow.models.http_endpoint.validate_path]),
        ),
        migrations.AddConstraint(
            model_name='engine',
            constraint=models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=('tenant_id', 'external_id'), name='_4_engine_tenant_id_external_id__1'),
        ),
    ]
