# Generated by Django 3.1.2 on 2020-12-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0012_auto_20201217_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowpermissions',
            options={'default_permissions': [], 'managed': False, 'permissions': (('system.edit', 'Allowed to edit system flows'), ('impl', 'Allowed to access flow implementation endpoints'))},
        ),
    ]
