# Generated by Django 3.1.2 on 2020-12-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0013_auto_20201217_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engine',
            options={'default_permissions': [], 'permissions': []},
        ),
    ]
