# Generated by Django 3.1.2 on 2020-12-18 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0015_auto_20201217_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engine',
            options={'permissions': []},
        ),
    ]
