# Generated by Django 3.1.2 on 2021-01-04 16:34

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0016_auto_20201218_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='engine',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flow.engine'),
        ),
        migrations.AddField(
            model_name='flow',
            name='system',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
