# Generated by Django 3.1.2 on 2021-01-04 16:40

from django.db import migrations, models
import skipper.core.models.validation
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0017_auto_20210104_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='external_id',
            field=models.CharField(default=uuid.uuid4, max_length=256, validators=[skipper.core.models.validation.external_id_validator_sql_safe]),
        ),
        migrations.RunSQL(f"""
        UPDATE _4_flow
        SET external_id = id
        """)
    ]
