# Generated by Django 3.1.2 on 2021-01-04 16:40

from django.db import migrations, models
import skipper.core.models.validation


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0018_flow_external_id_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='external_id',
            field=models.CharField(max_length=256, validators=[skipper.core.models.validation.external_id_validator_sql_safe]),
        ),
    ]
