# Generated by Django 3.1.2 on 2021-01-04 16:54

from django.db import migrations
import django.db.models.deletion
import django.db.models.expressions
import django_multitenant.fields  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0019_auto_20210104_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flow',
            options={'ordering': ['system', django.db.models.expressions.OrderBy(django.db.models.expressions.F('external_id'), nulls_last=True)], 'permissions': (('use', 'Allowed to use endpoint'),)},
        ),
        migrations.AlterField(
            model_name='flow',
            name='engine',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flow.engine'),
        ),
    ]
