# Generated by Django 3.1.2 on 2021-01-05 10:18

from django.db import migrations
import django.db.models.deletion
import django_multitenant.fields  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0020_auto_20210104_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='engine',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='flow.engine'),
        ),
    ]
