# Generated by Django 3.1.2 on 2021-01-08 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0023_auto_20210106_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='secret',
            field=models.TextField(default=uuid.uuid4),
        ),
    ]
