# Generated by Django 3.1.2 on 2021-01-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0024_engine_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='secret',
            field=models.TextField(),
        ),
    ]
