# Generated by Django 3.1.2 on 2021-01-08 16:38

from django.db import migrations, models
import skipper.flow.models.engine


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0025_auto_20210108_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='secret',
            field=models.TextField(default=skipper.flow.models.engine.gen_engine_secret),
        ),
    ]
