# Generated by Django 3.1.2 on 2021-01-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_tasklogentry'),
        ('flow', '0029_auto_20210111_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flow',
            new_name='HttpEndpoint',
        ),
        migrations.AlterModelOptions(
            name='flowpermissions',
            options={'default_permissions': [], 'managed': False, 'permissions': (('system.edit', 'Allowed to edit system flows'), ('impl', 'Allowed to access flow implementation endpoints'))},
        ),
        migrations.AlterModelTable(
            name='httpendpoint',
            table='_4_http_endpoint',
        ),
    ]
