# Generated by Django 3.1.2 on 2021-01-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0030_auto_20210111_2055'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='httpendpoint',
            name='_4_flow_tenant_id_external_id__1',
        ),
        migrations.AddConstraint(
            model_name='httpendpoint',
            constraint=models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=('tenant_id', 'external_id'), name='_4_http_endpoint_tenant_id_external_id__1'),
        ),
    ]
