# Generated by Django 3.1.2 on 2021-01-15 11:43

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0032_auto_20210115_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='httpendpoint',
            options={'ordering': ['system', django.db.models.expressions.OrderBy(django.db.models.expressions.F('external_id'), nulls_last=True)], 'permissions': [('http_endpoint_get_http_endpoint', 'Can run GET on entity http_endpoint and action http_endpoint'), ('http_endpoint_options_http_endpoint', 'Can run OPTIONS on entity http_endpoint on action http_endpoint'), ('http_endpoint_head_http_endpoint', 'Can run HEAD on entity http_endpoint on action http_endpoint'), ('http_endpoint_post_http_endpoint', 'Can run POST on entity http_endpoint on action http_endpoint'), ('http_endpoint_put_http_endpoint', 'Can run PUT on entity http_endpoint on action http_endpoint'), ('http_endpoint_patch_http_endpoint', 'Can run PATCH on entity http_endpoint on action http_endpoint'), ('http_endpoint_delete_http_endpoint', 'Can run DELETE on entity http_endpoint on action http_endpoint'), ('http_endpoint_get_permission', 'Can run GET on entity http_endpoint and action permission'), ('http_endpoint_options_permission', 'Can run OPTIONS on entity http_endpoint on action permission'), ('http_endpoint_head_permission', 'Can run HEAD on entity http_endpoint on action permission'), ('http_endpoint_post_permission', 'Can run POST on entity http_endpoint on action permission'), ('http_endpoint_put_permission', 'Can run PUT on entity http_endpoint on action permission'), ('http_endpoint_patch_permission', 'Can run PATCH on entity http_endpoint on action permission'), ('http_endpoint_delete_permission', 'Can run DELETE on entity http_endpoint on action permission'), ('use', 'Allowed to use endpoint')]},
        ),
    ]
