# Generated by Django 3.1.2 on 2020-11-19 19:03

from django.db import migrations, models
from typing import List, Any


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Any] = []

    operations = [
        migrations.CreateModel(
            name='TaskPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('dashboard', 'Allowed to view the task dashboard'),),
                'managed': False,
                'default_permissions': [],
            },
        ),
    ]
