# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. 
# If a copy of the MPL was not distributed with this file, 
# You can obtain one at https://mozilla.org/MPL/2.0/.
# This file is part of NF Compose
# [2019] - [2024] © NeuroForge GmbH & Co. KG

from typing import Any

from skipper.core.views import mixin
from skipper.core.views.mixin import HasTenantSetPermission


class AuthRestrictiveDjangoModelPermissions(mixin.RestrictiveDjangoModelPermissions):
    perms_map = {
        'GET': ['auth.view_%(model_name)s'],
        'OPTIONS': ['auth.view_%(model_name)s'],
        'HEAD': ['auth.view_%(model_name)s'],
        'POST': ['auth.add_%(model_name)s'],
        'PUT': ['auth.change_%(model_name)s'],
        'PATCH': ['auth.change_%(model_name)s'],
        'DELETE': ['auth.delete_%(model_name)s'],
    }


class AuthTenantViewMixin:
    permission_classes: Any = (AuthRestrictiveDjangoModelPermissions, HasTenantSetPermission)


generally_assignable_permissions = {
    "dataseries.ds_delete_check_external_ids",
    "dataseries.ds_delete_consumer",
    "dataseries.ds_delete_create_view",
    "dataseries.ds_delete_cube_sql",
    "dataseries.ds_delete_data_point",
    "dataseries.ds_delete_data_point_bulk",
    "dataseries.ds_delete_data_series",
    "dataseries.ds_delete_history_data_point",
    "dataseries.ds_delete_permission",
    "dataseries.ds_delete_prune_history",
    "dataseries.ds_delete_prune_metamodel",
    "dataseries.ds_delete_structure_element",
    "dataseries.ds_delete_truncate_data_series",
    "dataseries.ds_get_check_external_ids",
    "dataseries.ds_get_consumer",
    "dataseries.ds_get_create_view",
    "dataseries.ds_get_cube_sql",
    "dataseries.ds_get_data_point",
    "dataseries.ds_get_data_point_bulk",
    "dataseries.ds_get_data_series",
    "dataseries.ds_get_history_data_point",
    "dataseries.ds_get_permission",
    "dataseries.ds_get_prune_history",
    "dataseries.ds_get_prune_metamodel",
    "dataseries.ds_get_structure_element",
    "dataseries.ds_get_truncate_data_series",
    "dataseries.ds_head_check_external_ids",
    "dataseries.ds_head_consumer",
    "dataseries.ds_head_create_view",
    "dataseries.ds_head_cube_sql",
    "dataseries.ds_head_data_point",
    "dataseries.ds_head_data_point_bulk",
    "dataseries.ds_head_data_series",
    "dataseries.ds_head_history_data_point",
    "dataseries.ds_head_permission",
    "dataseries.ds_head_prune_history",
    "dataseries.ds_head_prune_metamodel",
    "dataseries.ds_head_structure_element",
    "dataseries.ds_head_truncate_data_series",
    "dataseries.ds_options_check_external_ids",
    "dataseries.ds_options_consumer",
    "dataseries.ds_options_create_view",
    "dataseries.ds_options_cube_sql",
    "dataseries.ds_options_data_point",
    "dataseries.ds_options_data_point_bulk",
    "dataseries.ds_options_data_series",
    "dataseries.ds_options_history_data_point",
    "dataseries.ds_options_permission",
    "dataseries.ds_options_prune_history",
    "dataseries.ds_options_prune_metamodel",
    "dataseries.ds_options_structure_element",
    "dataseries.ds_options_truncate_data_series",
    "dataseries.ds_patch_check_external_ids",
    "dataseries.ds_patch_consumer",
    "dataseries.ds_patch_create_view",
    "dataseries.ds_patch_cube_sql",
    "dataseries.ds_patch_data_point",
    "dataseries.ds_patch_data_point_bulk",
    "dataseries.ds_patch_data_series",
    "dataseries.ds_patch_history_data_point",
    "dataseries.ds_patch_permission",
    "dataseries.ds_patch_prune_history",
    "dataseries.ds_patch_prune_metamodel",
    "dataseries.ds_patch_structure_element",
    "dataseries.ds_patch_truncate_data_series",
    "dataseries.ds_post_check_external_ids",
    "dataseries.ds_post_consumer",
    "dataseries.ds_post_create_view",
    "dataseries.ds_post_cube_sql",
    "dataseries.ds_post_data_point",
    "dataseries.ds_post_data_point_bulk",
    "dataseries.ds_post_data_series",
    "dataseries.ds_post_history_data_point",
    "dataseries.ds_post_permission",
    "dataseries.ds_post_prune_history",
    "dataseries.ds_post_prune_metamodel",
    "dataseries.ds_post_structure_element",
    "dataseries.ds_post_truncate_data_series",
    "dataseries.ds_put_check_external_ids",
    "dataseries.ds_put_consumer",
    "dataseries.ds_put_create_view",
    "dataseries.ds_put_cube_sql",
    "dataseries.ds_put_data_point",
    "dataseries.ds_put_data_point_bulk",
    "dataseries.ds_put_data_series",
    "dataseries.ds_put_history_data_point",
    "dataseries.ds_put_permission",
    "dataseries.ds_put_prune_history",
    "dataseries.ds_put_prune_metamodel",
    "dataseries.ds_put_structure_element",
    "dataseries.ds_put_truncate_data_series",

    "dataseries.prune_data_series",
    "dataseries.storage_backend_data",

    "flow.engine_delete_access",
    "flow.engine_delete_engine",
    "flow.engine_delete_permission",
    "flow.engine_delete_secret",
    "flow.engine_get_access",
    "flow.engine_get_engine",
    "flow.engine_get_permission",
    "flow.engine_get_secret",
    "flow.engine_head_access",
    "flow.engine_head_engine",
    "flow.engine_head_permission",
    "flow.engine_head_secret",
    "flow.engine_options_access",
    "flow.engine_options_engine",
    "flow.engine_options_permission",
    "flow.engine_options_secret",
    "flow.engine_patch_access",
    "flow.engine_patch_engine",
    "flow.engine_patch_permission",
    "flow.engine_patch_secret",
    "flow.engine_post_access",
    "flow.engine_post_engine",
    "flow.engine_post_permission",
    "flow.engine_post_secret",
    "flow.engine_put_access",
    "flow.engine_put_engine",
    "flow.engine_put_permission",
    "flow.engine_put_secret",
    "flow.http_endpoint_delete_http_endpoint",
    "flow.http_endpoint_delete_permission",
    "flow.http_endpoint_get_http_endpoint",
    "flow.http_endpoint_get_permission",
    "flow.http_endpoint_head_http_endpoint",
    "flow.http_endpoint_head_permission",
    "flow.http_endpoint_options_http_endpoint",
    "flow.http_endpoint_options_permission",
    "flow.http_endpoint_patch_http_endpoint",
    "flow.http_endpoint_patch_permission",
    "flow.http_endpoint_post_http_endpoint",
    "flow.http_endpoint_post_permission",
    "flow.http_endpoint_put_http_endpoint",
    "flow.http_endpoint_put_permission",

    "flow.impl",
    #  "flow.system.edit", # explicitly not allow this, this is not something we want to allow in a multitenant setting
    "flow.use",

    "task.dashboard",

    "core.browse_api",

    # system permissions
    'auth.view_user',
    'auth.add_user',
    'auth.change_user',
    'auth.delete_user',

    'auth.view_group',
    'auth.add_group',
    'auth.change_group',
    'auth.delete_group'
}
