{
 "title": "NF Compose Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tenants",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nfrom _core_tenant "
    }
   ]
  },
  {
   "title": "DataSeries Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  tenant.name as tenant,\n  count(*)\nFROM _3_data_series dataseries\nJOIN _core_tenant tenant on dataseries.tenant_id = tenant.id\nWHERE dataseries.deleted_at IS NULL\nGROUP BY 1"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Consumer Event Success Throughput per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(event.last_updated_at, '1m') AS time,\n  tenant.name as tenant,\n  dataseries.external_id as dataseries,\n  consumer.name as consumer,\n  count(*) AS event_count\nFROM _3_consumer_event event\nJOIN _3_consumer consumer on event.consumer_id = consumer.id\nJOIN _3_data_series_consumer dataseries_consumer on consumer.id = dataseries_consumer.consumer_id\nJOIN _3_data_series dataseries on dataseries_consumer.data_series_id = dataseries.id\nJOIN _core_tenant tenant on dataseries.tenant_id = tenant.id\nWHERE $__timeFilter(event.last_updated_at) AND event.state = 'SUCCESS'\nGROUP BY 1,2,3,4\nORDER BY 1,2,3,4"
    }
   ]
  },
  {
   "title": "Consumer Events Creation per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(event.point_in_time, '1m') AS time,\n  tenant.name as tenant,\n  dataseries.external_id as dataseries,\n  consumer.name as consumer,\n  count(*) AS event_count\nFROM _3_consumer_event event\nJOIN _3_consumer consumer on event.consumer_id = consumer.id\nJOIN _3_data_series_consumer dataseries_consumer on consumer.id = dataseries_consumer.consumer_id\nJOIN _3_data_series dataseries on dataseries_consumer.data_series_id = dataseries.id\nJOIN _core_tenant tenant on dataseries.tenant_id = tenant.id\nWHERE $__timeFilter(event.point_in_time)\nGROUP BY 1,2,3,4\nORDER BY 1,2,3,4"
    }
   ]
  },
  {
   "title": "Uploaded Files in the System per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(lookup.point_in_time, '1m') AS time,\n  data_series.external_id AS data_series,\n  data_series_filefact.external_id as fact,\n  tenant.name as tenant,\n  count(*)\nFROM _3_file_lookup lookup\nJOIN _3_file_fact file_fact ON lookup.fact_id = file_fact.id\nJOIN _3_data_series_file_fact data_series_filefact ON file_fact.id = data_series_filefact.fact_id\nJOIN _3_data_series data_series ON data_series_filefact.data_series_id = data_series.id\nJOIN _core_tenant tenant ON data_series.tenant_id = tenant.id\nWHERE lookup.deleted_at IS NULL\nAND $__timeFilter(lookup.point_in_time)\nGROUP BY 1,2,3,4"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(lookup.point_in_time, '1m') AS time,\n  data_series.external_id AS data_series,\n  data_series_imagefact.external_id as fact,\n  tenant.name as tenant,\n  count(*)\nFROM _3_file_lookup lookup\nJOIN _3_image_fact image_fact ON lookup.fact_id = image_fact.id\nJOIN _3_data_series_image_fact data_series_imagefact ON image_fact.id = data_series_imagefact.fact_id\nJOIN _3_data_series data_series ON data_series_imagefact.data_series_id = data_series.id\nJOIN _core_tenant tenant ON data_series.tenant_id = tenant.id\nWHERE lookup.deleted_at IS NULL\nAND $__timeFilter(lookup.point_in_time)\nGROUP BY 1,2,3,4"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "subsystems health",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(last_check, '1m') AS time,\n  key,\n  count(health) as health\nFROM _5_healthcheck._5_subsystemhealth\nWHERE health = 'HEALTHY'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Failing Consumer Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(event.last_updated_at, '1m') AS time,\n  tenant.name as tenant,\n  dataseries.external_id as dataseries,\n  consumer.name as consumer,\n  count(*) AS event_count\nFROM _3_consumer_event event\nJOIN _3_consumer consumer on event.consumer_id = consumer.id\nJOIN _3_data_series_consumer dataseries_consumer on consumer.id = dataseries_consumer.consumer_id\nJOIN _3_data_series dataseries on dataseries_consumer.data_series_id = dataseries.id\nJOIN _core_tenant tenant on dataseries.tenant_id = tenant.id\nWHERE $__timeFilter(event.last_updated_at) AND (retries > 3 AND state = 'RETRY')\nGROUP BY 1,2,3,4\nORDER BY 1,2,3,4"
    }
   ]
  },
  {
   "title": "Consumer Events in State New",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(event.last_updated_at, '1m') AS time,\n  tenant.name as tenant,\n  dataseries.external_id as dataseries,\n  consumer.name as consumer,\n  count(*) AS event_count\nFROM _3_consumer_event event\nJOIN _3_consumer consumer on event.consumer_id = consumer.id\nJOIN _3_data_series_consumer dataseries_consumer on consumer.id = dataseries_consumer.consumer_id\nJOIN _3_data_series dataseries on dataseries_consumer.data_series_id = dataseries.id\nJOIN _core_tenant tenant on dataseries.tenant_id = tenant.id\nWHERE $__timeFilter(event.last_updated_at) AND state = 'NEW'\nGROUP BY 1,2,3,4\nORDER BY 1,2,3,4"
    }
   ]
  }
 ]
}