# Generated by Django 3.0.9 on 2020-09-18 06:56

from django.db import migrations, models
from typing import Any, List


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Any] = []

    operations = [
        migrations.CreateModel(
            name='SubSystemHealth',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('last_check', models.DateTimeField(null=True)),
                ('health', models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('UNHEALTHY', 'UNHEALTHY'), ('HEALTHY', 'HEALTHY')], default='UNKNOWN', max_length=100)),
            ],
        ),
    ]
