# Generated by Django 3.0.9 on 2020-09-18 10:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsystemhealth',
            name='errors',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='subsystemhealth',
            name='time_taken',
            field=models.FloatField(null=True),
        ),
        migrations.AlterModelTable(
            name='subsystemhealth',
            table='_5_subsystemhealth',
        ),
    ]
