# Generated by Django 3.0.9 on 2020-09-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20200918_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsystemhealth',
            old_name='errors',
            new_name='last_errors',
        ),
    ]
