# Generated by Django 3.0.9 on 2020-10-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20200918_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckDatabaseUser',
            fields=[
                ('role', models.CharField(max_length=63, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '_5_healthcheckdatabaseuser',
            },
        ),
    ]
