# Generated by Django 3.0.9 on 2020-10-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_healthcheckdatabaseuser'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE SCHEMA IF NOT EXISTS "_5_healthcheck";
            CREATE VIEW "_5_healthcheck"."_5_subsystemhealth" 
                AS SELECT * FROM "_5_subsystemhealth";
            """
        ),
    ]
