# Generated by Django 3.1.2 on 2020-10-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_healthcheck_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsystemhealth',
            name='last_errors',
            field=models.JSONField(null=True),  # type: ignore
        ),
    ]
