# Generated by Django 3.1.2 on 2020-10-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_auto_20201012_1940'),
    ]

    operations = [
        migrations.RunSQL('TRUNCATE "_5_subsystemhealth"')
    ]
