# Generated by Django 3.1.7 on 2021-04-21 13:39

from django.db import migrations, models
import skipper.core.models.softdelete


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_purge_old_healthchecks'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='healthcheckdatabaseuser',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.core.models.softdelete.SoftDeletionTenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='healthcheckdatabaseuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
