# Generated by Django 3.1.7 on 2021-04-21 13:39

from django.db import migrations
import skipper.core.models.softdelete


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_auto_20210421_1339'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='healthcheckdatabaseuser',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionManager(alive_only=False)),
                ('objects', skipper.core.models.softdelete.SoftDeletionManager()),
            ],
        ),
    ]
