# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. 
# If a copy of the MPL was not distributed with this file, 
# You can obtain one at https://mozilla.org/MPL/2.0/.
# This file is part of NF Compose
# [2019] - [2024] © NeuroForge GmbH & Co. KG

FROM python:3.11

# so celery immediately quits and does not wait around to get killed by docker
# this way it puts jobs back that were set to acks_late=True
ENV REMAP_SIGTERM=SIGQUIT

ARG CONTAINER_USER_ID
ARG CONTAINER_GROUP_ID

RUN apt-get update && apt-get install -y \
	sudo \
	vim \
	build-essential \
	libssl-dev \
	libffi-dev \
	cargo \
	pkg-config

RUN pip install setuptools==68.2.2
RUN pip install --upgrade pip==23.3.1
RUN pip install pipenv==2023.10.24
ENV PIPENV_IGNORE_VIRTUALENVS=1
ENV PIPENV_VENV_IN_PROJECT=1


RUN groupadd -g ${CONTAINER_GROUP_ID} devenv || echo "group with id ${CONTAINER_GROUP_ID} already exists, ignoring..."

RUN useradd -rm -d /home/skipper -s /bin/bash -g root -G sudo -u 9999 skipper
RUN useradd -rm -d /home/neuroforge -s /bin/bash -g root -G sudo -u "${CONTAINER_USER_ID}" -g "${CONTAINER_GROUP_ID}" neuroforge

RUN passwd -d skipper
RUN passwd -d neuroforge

RUN echo '%skipper ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
RUN echo '%neuroforge ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN apt-get install -y rsync

USER neuroforge

WORKDIR /neuroforge/skipper/

