# Generated by Django 4.0 on 2022-01-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name='DebugPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('telemetry.ui', 'Allowed to view the debug telemetry ui'),),
                'managed': False,
                'default_permissions': [],
            },
        ),
    ]
