# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. 
# If a copy of the MPL was not distributed with this file, 
# You can obtain one at https://mozilla.org/MPL/2.0/.
# This file is part of NF Compose
# [2019] - [2024] © NeuroForge GmbH & Co. KG


# Generated by Django 2.2.8 on 2020-01-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='optional',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
