# Generated by Django 2.2.8 on 2020-03-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0006_auto_20200213_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataseries',
            options={'permissions': [('ds_get_data_series', 'Can run GET on action data_series'), ('ds_options_data_series', 'Can run OPTIONS on action data_series'), ('ds_head_data_series', 'Can run HEAD on action data_series'), ('ds_post_data_series', 'Can run POST on action data_series'), ('ds_put_data_series', 'Can run PUT on action data_series'), ('ds_patch_data_series', 'Can run PATCH on action data_series'), ('ds_delete_data_series', 'Can run DELETE on action data_series'), ('ds_get_data_point', 'Can run GET on action data_point'), ('ds_options_data_point', 'Can run OPTIONS on action data_point'), ('ds_head_data_point', 'Can run HEAD on action data_point'), ('ds_post_data_point', 'Can run POST on action data_point'), ('ds_put_data_point', 'Can run PUT on action data_point'), ('ds_patch_data_point', 'Can run PATCH on action data_point'), ('ds_delete_data_point', 'Can run DELETE on action data_point'), ('ds_get_structure_element', 'Can run GET on action structure_element'), ('ds_options_structure_element', 'Can run OPTIONS on action structure_element'), ('ds_head_structure_element', 'Can run HEAD on action structure_element'), ('ds_post_structure_element', 'Can run POST on action structure_element'), ('ds_put_structure_element', 'Can run PUT on action structure_element'), ('ds_patch_structure_element', 'Can run PATCH on action structure_element'), ('ds_delete_structure_element', 'Can run DELETE on action structure_element'), ('ds_get_create_view', 'Can run GET on action create_view'), ('ds_options_create_view', 'Can run OPTIONS on action create_view'), ('ds_head_create_view', 'Can run HEAD on action create_view'), ('ds_post_create_view', 'Can run POST on action create_view'), ('ds_put_create_view', 'Can run PUT on action create_view'), ('ds_patch_create_view', 'Can run PATCH on action create_view'), ('ds_delete_create_view', 'Can run DELETE on action create_view'), ('ds_get_cube_sql', 'Can run GET on action cube_sql'), ('ds_options_cube_sql', 'Can run OPTIONS on action cube_sql'), ('ds_head_cube_sql', 'Can run HEAD on action cube_sql'), ('ds_post_cube_sql', 'Can run POST on action cube_sql'), ('ds_put_cube_sql', 'Can run PUT on action cube_sql'), ('ds_patch_cube_sql', 'Can run PATCH on action cube_sql'), ('ds_delete_cube_sql', 'Can run DELETE on action cube_sql'), ('ds_get_data_point_bulk', 'Can run GET on action data_point_bulk'), ('ds_options_data_point_bulk', 'Can run OPTIONS on action data_point_bulk'), ('ds_head_data_point_bulk', 'Can run HEAD on action data_point_bulk'), ('ds_post_data_point_bulk', 'Can run POST on action data_point_bulk'), ('ds_put_data_point_bulk', 'Can run PUT on action data_point_bulk'), ('ds_patch_data_point_bulk', 'Can run PATCH on action data_point_bulk'), ('ds_delete_data_point_bulk', 'Can run DELETE on action data_point_bulk'), ('ds_get_check_external_ids', 'Can run GET on action check_external_ids'), ('ds_options_check_external_ids', 'Can run OPTIONS on action check_external_ids'), ('ds_head_check_external_ids', 'Can run HEAD on action check_external_ids'), ('ds_post_check_external_ids', 'Can run POST on action check_external_ids'), ('ds_put_check_external_ids', 'Can run PUT on action check_external_ids'), ('ds_patch_check_external_ids', 'Can run PATCH on action check_external_ids'), ('ds_delete_check_external_ids', 'Can run DELETE on action check_external_ids')]},
        ),
        migrations.AlterModelOptions(
            name='dataseries_dimension',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='dataseries_floatfact',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='dataseries_imagefact',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='dataseries_jsonfact',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='dataseries_stringfact',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='dataseries_textfact',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='dataseries_timestampfact',
            options={'default_permissions': []},
        ),
    ]
