# Generated by Django 2.2.8 on 2020-03-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0007_auto_20200306_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataseries',
            name='allow_extra_fields',
            field=models.BooleanField(default=False),
        ),
    ]
