# Generated by Django 2.2.8 on 2020-03-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0008_dataseries_allow_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataseries',
            name='external_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dataseries_dimension',
            name='external_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dataseries_floatfact',
            name='external_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dataseries_imagefact',
            name='external_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dataseries_jsonfact',
            name='external_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dataseries_stringfact',
            name='external_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dataseries_textfact',
            name='external_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dataseries_timestampfact',
            name='external_id',
            field=models.CharField(max_length=256),
        ),
    ]
