# Generated by Django 2.2.8 on 2020-03-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0009_auto_20200311_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSeriesPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('node_red_etl', 'Allowed to use the node red ETL interface'),),
                'managed': False,
                'default_permissions': [],
            },
        ),
    ]
