# Generated by Django 2.2.8 on 2020-05-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0013_dataseries_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataseries',
            name='backend',
            field=models.CharField(choices=[('DYNAMIC_SQL_MATERIALIZED', 'DYNAMIC_SQL_MATERIALIZED'), ('DYNAMIC_SQL_V1', 'DYNAMIC_SQL_V1')], default='DYNAMIC_SQL_MATERIALIZED', max_length=255),
        ),
    ]
