# Generated by Django 2.2.12 on 2020-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0014_auto_20200522_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataseries',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
