# Generated by Django 3.0.7 on 2020-07-24 09:10

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.manager
import django_multitenant.mixins  # type: ignore
from django.db import migrations, models

import skipper.core.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200611_1255'),
        ('dataseries', '0020_auto_20200702_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('point_in_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=256)),
                ('target', models.URLField(max_length=1024)),
                ('headers', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Tenant')),
            ],
            options={
                'db_table': '_3_consumer',
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DataSeries_Consumer',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('point_in_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=256)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumer', skipper.core.models.fields.UniqueFKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataseries.Consumer')),
                ('data_series', skipper.core.models.fields.FKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataseries.DataSeries')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Tenant')),
            ],
            options={
                'db_table': '_3_data_series_consumer',
                'default_permissions': [],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='dataseries_consumer',
            constraint=models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=('tenant_id', 'data_series', 'external_id'), name='_3_data_series_consumer_external_id_1'),
        ),
        migrations.AddConstraint(
            model_name='dataseries_consumer',
            constraint=models.UniqueConstraint(condition=models.Q(deleted_at__isnull=False), fields=('tenant_id', 'data_series', 'external_id', 'deleted_at'), name='_3_data_series_consumer_external_id_2'),
        ),
        migrations.AddConstraint(
            model_name='dataseries_consumer',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'id'), name='_3_data_series_consumer_tenant_id_id_0'),
        ),
        migrations.AddConstraint(
            model_name='consumer',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'id'), name='_3_consumer_tenant_id_id_0'),
        ),
    ]
