# Generated by Django 3.0.7 on 2020-07-24 16:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.mixins  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tenantjob'),
        ('dataseries', '0022_auto_20200724_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('retries', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('NEW', 'NEW'), ('RETRY', 'RETRY'), ('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('DATA_POINT_CHANGED', 'DATA_POINT_CHANGED'), ('DATA_POINT_DELETED', 'DATA_POINT_DELETED')], max_length=100)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataseries.Consumer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Tenant')),
            ],
            options={
                'db_table': '_3_consumer_event',
            },
            bases=(models.Model, django_multitenant.mixins.TenantModelMixin),
        ),
    ]
