# Generated by Django 3.0.7 on 2020-07-25 11:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0023_consumerevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerevent',
            name='inserted_at',
        ),
        migrations.AddField(
            model_name='consumerevent',
            name='backoff_cycles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumerevent',
            name='backoff_delay',
            field=models.DurationField(default=datetime.timedelta(seconds=30)),
        ),
        migrations.AddField(
            model_name='consumerevent',
            name='backoff_every',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='consumerevent',
            name='handle_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='consumerevent',
            name='point_in_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumerevent',
            name='retries_in_cycle',
            field=models.IntegerField(default=0),
        ),
    ]
