# Generated by Django 3.0.7 on 2020-07-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0024_auto_20200725_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='timeout',
            field=models.FloatField(default=60),
        ),
    ]
