# Generated by Django 3.0.7 on 2020-07-25 15:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0025_consumer_timeout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerevent',
            name='backoff_delay',
        ),
        migrations.RemoveField(
            model_name='consumerevent',
            name='backoff_every',
        ),
        migrations.RemoveField(
            model_name='consumerevent',
            name='max_retries',
        ),
        migrations.AddField(
            model_name='consumer',
            name='retry_backoff_delay',
            field=models.DurationField(default=datetime.timedelta(seconds=30)),
        ),
        migrations.AddField(
            model_name='consumer',
            name='retry_backoff_every',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='consumer',
            name='retry_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='timeout',
            field=models.FloatField(default=60, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
