# Generated by Django 3.0.7 on 2020-07-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0026_auto_20200725_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerevent',
            name='exception',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumerevent',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumerevent',
            name='status_code',
            field=models.IntegerField(null=True),
        ),
    ]
