# Generated by Django 3.0.7 on 2020-07-31 08:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import skipper.core.models.fields
import skipper.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0028_consumerevent_response_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerevent',
            name='response_headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True, validators=[skipper.core.validators.JSONSchemaValidator(limit_value={'additionalProperties': {'type': 'string'}, 'properties': {}, 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='consumerevent',
            name='payload',
            field=skipper.core.models.fields.EmptyDictNotBlankJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='headers',
            field=skipper.core.models.fields.EmptyDictNotBlankJSONField(default=dict, null=True, validators=[skipper.core.validators.JSONSchemaValidator(limit_value={'additionalProperties': {'type': 'string'}, 'properties': {}, 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='consumerevent',
            name='response_headers',
            field=skipper.core.models.fields.EmptyDictNotBlankJSONField(null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True, validators=[skipper.core.validators.JSONSchemaValidator(limit_value={'additionalProperties': {'type': 'string'}, 'properties': {}, 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='headers',
            field=skipper.core.models.fields.EmptyDictNotBlankJSONField(default=dict, null=True, validators=[skipper.core.validators.JSONSchemaValidator(limit_value={'additionalProperties': {'type': 'string'}, 'properties': {}, 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='consumerevent',
            name='handle_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumerevent',
            name='payload',
            field=skipper.core.models.fields.EmptyDictNotBlankJSONField(validators=[skipper.core.validators.JSONSchemaValidator(limit_value={'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='consumerevent',
            name='response_headers',
            field=skipper.core.models.fields.EmptyDictNotBlankJSONField(blank=True, null=True, validators=[skipper.core.validators.JSONSchemaValidator(limit_value={'additionalProperties': {'type': 'string'}, 'properties': {}, 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='consumerevent',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
