# Generated by Django 3.0.7 on 2020-08-01 11:09

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_multitenant.mixins  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200731_0920'),
        ('dataseries', '0029_auto_20200729_2251_squashed_0035_auto_20200731_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostgresAnalyticsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(max_length=63, unique=True)),
                ('tenant_global_read', models.BooleanField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Tenant')),
            ],
            options={
                'db_table': '_3_postgresanalyticsuser',
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
