# Generated by Django 3.0.7 on 2020-08-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0030_postgresanalyticsuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgresanalyticsuser',
            name='role',
            field=models.CharField(max_length=63),
        ),
    ]
