# Generated by Django 3.0.7 on 2020-08-01 11:09

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_multitenant.mixins  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200731_0920'),
        ('dataseries', '0031_auto_20200801_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostgresAnalyticsUser'
        )
    ]
