# Generated by Django 3.0.7 on 2020-08-06 17:15

from django.db import migrations
import django.db.models.deletion
import django_multitenant.fields  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0033_postgresanalyticsuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerevent',
            name='consumer',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataseries.Consumer'),
        ),
    ]
