# Generated by Django 3.0.9 on 2020-09-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0035_auto_20200828_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='health',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('RETRY', 'RETRY'), ('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], default='UNKNOWN', max_length=100),
        ),
    ]
