# Generated by Django 3.0.9 on 2020-09-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0036_consumer_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='health',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('UNHEALTHY', 'UNHEALTHY'), ('HEALTHY', 'HEALTHY')], default='UNKNOWN', max_length=100),
        ),
    ]
