# Generated by Django 3.1.2 on 2020-10-22 23:17

from django.db import migrations
import skipper.core.models.softdelete
import skipper.dataseries.models.metamodel.django_base


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0037_auto_20200917_1654'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='booleanfact',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='consumer',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dataseries',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dataseries_booleanfact',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dataseries_consumer',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dataseries_dimension',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dataseries_filefact',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dataseries_floatfact',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dataseries_imagefact',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dataseries_jsonfact',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dataseries_stringfact',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dataseries_textfact',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dataseries_timestampfact',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dimension',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='filefact',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='floatfact',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='imagefact',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='jsonfact',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='postgresanalyticsuser',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.core.models.softdelete.SoftDeletionTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='stringfact',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='textfact',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='timestampfact',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
    ]
