# Generated by Django 3.1.2 on 2020-10-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0038_auto_20201016_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataseries',
            name='backend',
            field=models.CharField(choices=[('DYNAMIC_SQL_MATERIALIZED', 'DYNAMIC_SQL_MATERIALIZED'), ('DYNAMIC_SQL_MATERIALIZED_FLAT_HISTORY', 'DYNAMIC_SQL_MATERIALIZED_FLAT_HISTORY'), ('DYNAMIC_SQL_V1', 'DYNAMIC_SQL_V1')], default='DYNAMIC_SQL_MATERIALIZED', max_length=255),
        ),
    ]
