# Generated by Django 3.1.2 on 2020-10-23 12:45

from django.db import migrations
from typing import List, Any


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0038_auto_20201022_2317'),
        ('dataseries', '0040_auto_20201020_2253'),
    ]

    operations: List[Any] = [
    ]
