# Generated by Django 3.1.2 on 2020-12-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0043_auto_20201129_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitionbyuuid',
            name='child_table_schema',
            field=models.CharField(max_length=63, null=True),
        ),
    ]
