# Generated by Django 3.1.2 on 2020-12-05 11:31

from django.db import migrations
import skipper.core.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0044_partitionbyuuid_child_table_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataseries',
            name='extra_config',
            field=skipper.core.models.fields.EmptyDictNotBlankJSONField(default=dict),
        ),
    ]
