# Generated by Django 3.1.2 on 2020-12-05 12:38

from django.db import migrations
import skipper.core.models.fields
import skipper.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0045_dataseries_extra_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='headers',
            field=skipper.core.models.fields.EmptyDictNotBlankJSONField(default=dict, null=True, validators=[skipper.core.validators.JSONSchemaValidator(json_schema_data=skipper.core.validators.JSONSchemaData(definitions=None, schema={'additionalProperties': {'type': 'string'}, 'properties': {}, 'type': 'object'}))]),
        ),
        migrations.AlterField(
            model_name='consumerevent',
            name='payload',
            field=skipper.core.models.fields.EmptyDictNotBlankJSONField(validators=[skipper.core.validators.JSONSchemaValidator(json_schema_data=skipper.core.validators.JSONSchemaData(definitions=None, schema={'type': 'object'}))]),
        ),
        migrations.AlterField(
            model_name='consumerevent',
            name='response_headers',
            field=skipper.core.models.fields.EmptyDictNotBlankJSONField(blank=True, null=True, validators=[skipper.core.validators.JSONSchemaValidator(json_schema_data=skipper.core.validators.JSONSchemaData(definitions=None, schema={'additionalProperties': {'type': 'string'}, 'properties': {}, 'type': 'object'}))]),
        ),
    ]
