# Generated by Django 3.1.2 on 2020-12-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0049_auto_20201205_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataseriespermissions',
            options={'default_permissions': [], 'managed': False, 'permissions': (('node_red_etl', 'Allowed to use the node red ETL interface (node_red_etl)'), ('storage_backend_data', 'Allowed to view metadata of the backends (storage_backend_data)'), ('prune_data_series', 'Allowed to prune old data_series (prune_data_series)'))},
        ),
    ]
