# Generated by Django 3.1.2 on 2020-12-11 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields  # type: ignore
import django_multitenant.mixins  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_tasklogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataseries', '0050_auto_20201210_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField(db_index=True)),
                ('data', models.JSONField()),  # type: ignore
                ('last_error', models.JSONField(default=None, null=True)),  # type: ignore
                ('record_source', models.TextField()),
                ('data_series', django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataseries.dataseries')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '_3_async_data',
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
