# Generated by Django 3.1.2 on 2020-12-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0052_auto_20201211_1954'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taskdata',
            table='_3_task_data',
        ),
    ]
