# Generated by Django 3.1.2 on 2020-12-12 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataseries', '0053_auto_20201211_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='data_series',
            field=django_multitenant.fields.TenantForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='dataseries.dataseries'),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
