# Generated by Django 3.1.2 on 2020-12-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_tasklogentry'),
        ('dataseries', '0054_auto_20201212_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tenant'),
        ),
    ]
