# Generated by Django 3.1.2 on 2020-12-12 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_delete_tasklogentry'),
        ('dataseries', '0055_auto_20201212_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='user',
            field=models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
