# Generated by Django 3.1.2 on 2020-12-17 13:36

from django.db import migrations, models
import skipper.core.models.validation


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0057_auto_20201212_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataseries',
            name='external_id',
            field=models.CharField(max_length=256, validators=[skipper.core.models.validation.external_id_validator_sql_safe]),
        ),
        migrations.AlterField(
            model_name='dataseries_booleanfact',
            name='external_id',
            field=models.CharField(max_length=256, validators=[skipper.core.models.validation.external_id_validator_sql_safe]),
        ),
        migrations.AlterField(
            model_name='dataseries_consumer',
            name='external_id',
            field=models.CharField(max_length=256, validators=[skipper.core.models.validation.external_id_validator_sql_safe]),
        ),
        migrations.AlterField(
            model_name='dataseries_dimension',
            name='external_id',
            field=models.CharField(max_length=256, validators=[skipper.core.models.validation.external_id_validator_sql_safe]),
        ),
        migrations.AlterField(
            model_name='dataseries_filefact',
            name='external_id',
            field=models.CharField(max_length=256, validators=[skipper.core.models.validation.external_id_validator_sql_safe]),
        ),
        migrations.AlterField(
            model_name='dataseries_floatfact',
            name='external_id',
            field=models.CharField(max_length=256, validators=[skipper.core.models.validation.external_id_validator_sql_safe]),
        ),
        migrations.AlterField(
            model_name='dataseries_imagefact',
            name='external_id',
            field=models.CharField(max_length=256, validators=[skipper.core.models.validation.external_id_validator_sql_safe]),
        ),
        migrations.AlterField(
            model_name='dataseries_jsonfact',
            name='external_id',
            field=models.CharField(max_length=256, validators=[skipper.core.models.validation.external_id_validator_sql_safe]),
        ),
        migrations.AlterField(
            model_name='dataseries_stringfact',
            name='external_id',
            field=models.CharField(max_length=256, validators=[skipper.core.models.validation.external_id_validator_sql_safe]),
        ),
        migrations.AlterField(
            model_name='dataseries_textfact',
            name='external_id',
            field=models.CharField(max_length=256, validators=[skipper.core.models.validation.external_id_validator_sql_safe]),
        ),
        migrations.AlterField(
            model_name='dataseries_timestampfact',
            name='external_id',
            field=models.CharField(max_length=256, validators=[skipper.core.models.validation.external_id_validator_sql_safe]),
        ),
    ]
