# Generated by Django 3.1.2 on 2020-12-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0061_auto_20201220_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleanfact',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dataseries',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dataseries_booleanfact',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dataseries_consumer',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dataseries_dimension',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dataseries_filefact',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dataseries_floatfact',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dataseries_imagefact',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dataseries_jsonfact',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dataseries_stringfact',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dataseries_textfact',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dataseries_timestampfact',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='filefact',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='floatfact',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='imagefact',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='jsonfact',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='stringfact',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='textfact',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='timestampfact',
            name='api_version',
            field=models.IntegerField(default=2),
        ),
    ]
