# Generated by Django 3.1.2 on 2020-12-20 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0062_auto_20201220_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booleanfact',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='dataseries',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='dataseries_booleanfact',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='dataseries_consumer',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='dataseries_dimension',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='dataseries_filefact',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='dataseries_floatfact',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='dataseries_imagefact',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='dataseries_jsonfact',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='dataseries_stringfact',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='dataseries_textfact',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='dataseries_timestampfact',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='dimension',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='filefact',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='floatfact',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='imagefact',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='jsonfact',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='stringfact',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='textfact',
            old_name='api_version',
            new_name='metamodel_version',
        ),
        migrations.RenameField(
            model_name='timestampfact',
            old_name='api_version',
            new_name='metamodel_version',
        ),
    ]
