# Generated by Django 3.1.2 on 2021-02-23 17:35

from django.db import migrations
import django.db.models.deletion
import django_multitenant.fields  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0066_auto_20201229_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerevent',
            name='consumer',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataseries.consumer'),
        ),
    ]
