# Generated by Django 3.2.2 on 2021-05-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0068_taskdata_sub_clock'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerevent',
            name='sub_clock',
            field=models.BigIntegerField(null=True),
        ),
    ]
