# Generated by Django 3.2.2 on 2021-07-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0069_consumerevent_sub_clock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataseries',
            name='backend',
            field=models.CharField(choices=[('DYNAMIC_SQL_MATERIALIZED', 'DYNAMIC_SQL_MATERIALIZED'), ('DYNAMIC_SQL_NO_HISTORY', 'DYNAMIC_SQL_NO_HISTORY'), ('DYNAMIC_SQL_MATERIALIZED_FLAT_HISTORY', 'DYNAMIC_SQL_MATERIALIZED_FLAT_HISTORY'), ('DYNAMIC_SQL_V1', 'DYNAMIC_SQL_V1')], default='DYNAMIC_SQL_MATERIALIZED', max_length=255),
        ),
    ]
