# Generated by Django 3.1.8 on 2021-08-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0071_file_lookup_20210805_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelookup',
            name='file_name',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='filelookup',
            index=models.Index(fields=['file_name'], name='file_name_lookup'),
        ),
    ]
