# Generated by Django 3.1.8 on 2021-08-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0072_auto_20210805_1123'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='filelookup',
            name='unique_file_lookup',
        ),
        migrations.RemoveIndex(
            model_name='filelookup',
            name='file_name_lookup',
        ),
        migrations.AddIndex(
            model_name='filelookup',
            index=models.Index(fields=['file_name'], name='file_lookup_name_lookup'),
        ),
        migrations.AddConstraint(
            model_name='filelookup',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'data_series_id', 'fact_id', 'data_point_id', 'point_in_time', 'sub_clock'), name='file_lookup_unique_file_lookup'),
        ),
    ]
