# Generated by Django 3.1.8 on 2021-08-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0073_auto_20210805_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='sub_clock',
            field=models.BigIntegerField(default=-1),
        ),
    ]
