# Generated by Django 3.1.8 on 2021-08-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0074_auto_20210805_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='sub_clock',
            field=models.BigIntegerField(),
        ),
    ]
