# Generated by Django 3.2.5 on 2021-08-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0075_auto_20210805_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleanfact',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='dataseries',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='dataseries_booleanfact',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='dataseries_consumer',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='dataseries_dimension',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='dataseries_filefact',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='dataseries_floatfact',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='dataseries_imagefact',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='dataseries_jsonfact',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='dataseries_stringfact',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='dataseries_textfact',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='dataseries_timestampfact',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='filefact',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='floatfact',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='imagefact',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='jsonfact',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='stringfact',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='textfact',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='timestampfact',
            name='metamodel_version',
            field=models.IntegerField(default=3),
        ),
    ]
