# Generated by Django 3.2.7 on 2021-12-02 10:18

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.mixins # type: ignore
import skipper.core.models.fields
import skipper.core.models.softdelete
import skipper.dataseries.models.metamodel.django_base


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_tenantpostgresqueuejob_args'),
        ('dataseries', '0079_index_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefinedIndex_Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('point_in_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('metamodel_version', models.IntegerField(default=4)),
                ('target_id', models.UUIDField(default=None, editable=False)),
                ('target_type', models.CharField(choices=[('FLOAT_FACT', 'FLOAT_FACT'), ('STRING_FACT', 'STRING_FACT'), ('TEXT_FACT', 'TEXT_FACT'), ('TIMESTAMP_FACT', 'TIMESTAMP_FACT'), ('IMAGE_FACT', 'IMAGE_FACT'), ('JSON_FACT', 'JSON_FACT'), ('BOOLEAN_FACT', 'BOOLEAN_FACT'), ('FILE_FACT', 'FILE_FACT'), ('DIMENSION', 'DIMENSION')], max_length=256)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tenant')),
                ('user_defined_index', skipper.core.models.fields.FKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataseries.userdefinedindex')),
            ],
            options={
                'db_table': '_3_user_defined_index_target',
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.dataseries.models.metamodel.django_base.MetaModelSoftDeletionManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='userdefinedindex_target',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'id'), name='_3_user_defined_index_target_tenant_id_id_0'),
        ),
    ]
