# Generated by Django 3.2.7 on 2021-12-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0080_index_targeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefinedindex_target',
            name='target_position_in_index_order',
            field=models.IntegerField(default=-1, editable=False),
            preserve_default=False,
        ),
    ]
