# Generated by Django 3.2.10 on 2021-12-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0081_index_target_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdefinedindex_target',
            unique_together={('user_defined_index', 'target_position_in_index_order'), ('user_defined_index', 'target_id')},
        ),
    ]
