# Generated by Django 3.2.10 on 2021-12-30 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0082_index_target_unique_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexByUUID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.UUIDField(default=None, editable=False)),
                ('source_type', models.CharField(choices=[('USER_DEFINED_INDEX', 'USER_DEFINED_INDEX')], max_length=256)),
                ('db_name', models.CharField(default=None, max_length=63)),
                ('target_table', models.CharField(default=None, max_length=63)),
            ],
        ),
        migrations.AddConstraint(
            model_name='indexbyuuid',
            constraint=models.UniqueConstraint(fields=('db_name',), name='unique_index_db_name'),
        ),
    ]
