# Generated by Django 4.0 on 2021-12-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0082_index_target_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdefinedindex_target',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
