# Generated by Django 4.0 on 2021-12-31 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0083_alter_userdefinedindex_target_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdefinedindex_target',
            name='id',
        ),
        migrations.AddField(
            model_name='userdefinedindex_target',
            name='new_idx',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
