# Generated by Django 4.0 on 2021-12-31 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0083_indexbyuuid'),
        ('dataseries', '0085_rename_new_idx_userdefinedindex_target_id'),
    ]

    operations = []  # type: ignore
