# Generated by Django 4.0 on 2022-01-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0086_merge_20211231_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexbyuuid',
            name='target_table_type',
            field=models.CharField(choices=[('MATERIALIZED', 'MATERIALIZED'), ('FLAT_HISTORY', 'FLAT_HISTORY')], default='MATERIALIZED', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='indexbyuuid',
            unique_together={('source_id', 'target_table_type')},
        ),
        migrations.AlterModelTable(
            name='indexbyuuid',
            table='_3_index_by_uuid',
        ),
    ]
