# Generated by Django 4.0.3 on 2022-04-15 15:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_tenant_user_tenant_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataseries', '0087_indexbyuuid_target_table_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskData',
            new_name='BulkInsertTaskData',
        ),
    ]
