# Generated by Django 4.0.3 on 2022-04-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0088_rename_taskdata_bulkinserttaskdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bulkinserttaskdata',
            table='_3_bulk_insert_task_data',
        ),
    ]
