# Generated by Django 4.0.3 on 2022-04-15 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields # type: ignore
import django_multitenant.mixins # type: ignore
import skipper.core.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_tenant_user_tenant_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataseries', '0089_alter_bulkinserttaskdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaModelTaskData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task', models.TextField()),
                ('point_in_time', models.DateTimeField(db_index=True)),
                ('data', models.JSONField(encoder=skipper.core.models.fields.JSONEncoder)),  # type: ignore
                ('last_error', models.JSONField(default=None, null=True)),  # type: ignore
                ('record_source', models.TextField()),
                ('data_series', django_multitenant.fields.TenantForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='dataseries.dataseries')),
                ('tenant', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tenant')),
                ('user', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '_3_meta_model_task_data',
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
