# Generated by Django 4.1.9 on 2023-05-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0092_displaydatapoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataseries',
            name='backend',
            field=models.CharField(choices=[('DYNAMIC_SQL_MATERIALIZED', 'DYNAMIC_SQL_MATERIALIZED'), ('DYNAMIC_SQL_NO_HISTORY', 'DYNAMIC_SQL_NO_HISTORY'), ('DYNAMIC_SQL_MATERIALIZED_FLAT_HISTORY', 'DYNAMIC_SQL_MATERIALIZED_FLAT_HISTORY'), ('DYNAMIC_SQL_V1', 'DYNAMIC_SQL_V1')], default='DYNAMIC_SQL_MATERIALIZED_FLAT_HISTORY', max_length=255),
        ),
    ]
