# Generated by Django 4.2.7 on 2024-01-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0095_alter_dataseries_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='mode',
            field=models.CharField(choices=[('IN_ORDER', 'IN_ORDER'), ('IN_ORDER_NON_BLOCKING', 'IN_ORDER_NON_BLOCKING')], default='IN_ORDER', max_length=100),
        ),
    ]
