# Generated by Django 4.2.7 on 2024-01-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0096_consumer_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerevent',
            name='retries',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
