# Generated by Django 5.0.2 on 2024-03-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataseries', '0097_alter_consumerevent_retries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='health',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('UNHEALTHY', 'UNHEALTHY'), ('HEALTHY', 'HEALTHY'), ('RATE_LIMIT', 'RATE_LIMIT')], default='UNKNOWN', max_length=100),
        ),
    ]
