# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. 
# If a copy of the MPL was not distributed with this file, 
# You can obtain one at https://mozilla.org/MPL/2.0/.
# This file is part of NF Compose
# [2019] - [2024] © NeuroForge GmbH & Co. KG


# Generated by Django 2.2.8 on 2020-01-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_globalpermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant_group',
            name='system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant_user',
            name='system',
            field=models.BooleanField(default=False),
        ),
    ]
