# Generated by Django 2.2.8 on 2020-03-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_allowedloginredirecthost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpermissions',
            options={'default_permissions': [], 'managed': False, 'permissions': (('browse_api', 'Browse API'),)},
        ),
    ]
