# Generated by Django 3.0.7 on 2020-07-24 11:20

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.functions
from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.mixins  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200611_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.contrib.postgres.functions.TransactionNow)),
                ('execute_at', models.DateTimeField(default=django.contrib.postgres.functions.TransactionNow)),
                ('priority', models.IntegerField(default=0, help_text='Jobs with higher priority will be processed first.')),
                ('task', models.CharField(max_length=255)),
                ('args', django.contrib.postgres.fields.jsonb.JSONField()),
                ('globally_unique_identifier', models.CharField(max_length=1024, null=True, unique=True)),
                ('queue', models.CharField(help_text='Use a unique name to represent each queue.', max_length=1024)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Tenant')),
            ],
            options={
                'db_table': '_core_tenant_job',
            },
            bases=(models.Model, django_multitenant.mixins.TenantModelMixin),
        ),
    ]
