# Generated by Django 3.0.7 on 2020-07-26 12:01

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tenantjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.contrib.postgres.functions.TransactionNow)),
                ('execute_at', models.DateTimeField(default=django.contrib.postgres.functions.TransactionNow)),
                ('priority', models.IntegerField(default=0, help_text='Jobs with higher priority will be processed first.')),
                ('task', models.CharField(max_length=255)),
                ('args', django.contrib.postgres.fields.jsonb.JSONField()),
                ('globally_unique_identifier', models.CharField(max_length=1024, null=True, unique=True)),
                ('queue', models.CharField(help_text='Use a unique name to represent each queue.', max_length=1024)),
            ],
            options={
                'db_table': '_core_job',
            },
        ),
    ]
