# Generated by Django 3.0.7 on 2020-07-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200726_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultJob',
        ),
    ]
