# Generated by Django 3.0.7 on 2020-07-31 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_defaultjob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TenantJob',
            new_name='TenantPostgresQueueJob',
        ),
    ]
