# Generated by Django 3.0.7 on 2020-07-31 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200731_0920'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tenantpostgresqueuejob',
            table='_core_tenant_pgq_job',
        ),
    ]
