# Generated by Django 3.0.7 on 2020-08-07 07:37

from django.db import migrations
import django.db.models.deletion
import django_multitenant.fields  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200731_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedloginredirecthost',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Tenant'),
        ),
    ]
