# Generated by Django 3.0.9 on 2020-09-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200807_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '_core_lock',
            },
        )
    ]
