# Generated by Django 3.0.9 on 2020-09-20 14:44
from django.apps.registry import Apps
from django.db import migrations
from typing import Any

import skipper.core.models.lock


def setup_locks(apps: Apps, schema_editor: Any) -> None:
    Lock = apps.get_model('core', 'Lock')
    Lock.objects.setup_locks()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_lock'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lock',
            managers=[
                ('objects', skipper.core.models.lock.LockManager()),
            ],
        ),
        migrations.RunPython(setup_locks)
    ]
