# Generated by Django 3.1.2 on 2020-10-22 23:17

from django.db import migrations
import skipper.core.models.softdelete


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200920_1444'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='allowedloginredirecthost',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionTenantManager(alive_only=False)),
                ('objects', skipper.core.models.softdelete.SoftDeletionTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='presharedtoken',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionManager(alive_only=False)),
                ('objects', skipper.core.models.softdelete.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tenant',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionManager(alive_only=False)),
                ('objects', skipper.core.models.softdelete.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tenant_group',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionManager(alive_only=False)),
                ('objects', skipper.core.models.softdelete.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tenant_user',
            managers=[
                ('all_objects', skipper.core.models.softdelete.SoftDeletionManager(alive_only=False)),
                ('objects', skipper.core.models.softdelete.SoftDeletionManager()),
            ],
        ),
    ]
