# Generated by Django 3.1.2 on 2020-11-20 17:44

from django.db import migrations, models
import skipper.core.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201022_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLogEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('point_in_time', models.DateTimeField(db_index=True)),
                ('payload', skipper.core.models.fields.EmptyDictNotBlankJSONField()),
                ('entry_type', models.CharField(choices=[('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], db_index=True, max_length=100)),
            ],
            options={
                'db_table': '_core_tasklogentry',
            },
        ),
    ]
