# Generated by Django 3.1.2 on 2020-11-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_tasklogentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklogentry',
            options={'verbose_name_plural': 'Task log entries'},
        ),
    ]
