# Generated by Django 3.1.2 on 2020-11-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201120_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskLogEntry',
        ),
    ]
