# Generated by Django 3.2.7 on 2021-10-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_tasklogentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantpostgresqueuejob',
            name='args',
            field=models.JSONField(),  # type: ignore
        ),
    ]
