# Generated by Django 4.0 on 2021-12-31 19:54

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor): # type: ignore
    PreSharedToken = apps.get_model('core', 'PreSharedToken')
    for row in PreSharedToken.objects.all():
        row.new_idx = uuid.uuid4()
        row.save(update_fields=['new_idx'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_tenantpostgresqueuejob_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presharedtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='presharedtoken',
            name='new_idx',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
