# Generated by Django 4.0 on 2021-12-31 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_presharedtoken_id_presharedtoken_new_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presharedtoken',
            old_name='new_idx',
            new_name='id',
        ),
    ]
