# Generated by Django 4.0.3 on 2022-03-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_new_idx_presharedtoken_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'permissions': [('tenant_get_tenant', 'Can run GET on entity tenant and action tenant'), ('tenant_options_tenant', 'Can run OPTIONS on entity tenant on action tenant'), ('tenant_head_tenant', 'Can run HEAD on entity tenant on action tenant'), ('tenant_post_tenant', 'Can run POST on entity tenant on action tenant'), ('tenant_put_tenant', 'Can run PUT on entity tenant on action tenant'), ('tenant_patch_tenant', 'Can run PATCH on entity tenant on action tenant'), ('tenant_delete_tenant', 'Can run DELETE on entity tenant on action tenant')]},
        ),
    ]
