# Generated by Django 4.0.3 on 2022-04-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_tenant_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant_user',
            name='tenant_manager',
            field=models.BooleanField(default=False),
        ),
    ]
