# Generated by Django 4.0.4 on 2022-06-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_tenant_user_tenant_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('user_get_user', 'Can run GET on entity user and action user'), ('user_options_user', 'Can run OPTIONS on entity user on action user'), ('user_head_user', 'Can run HEAD on entity user on action user'), ('user_post_user', 'Can run POST on entity user on action user'), ('user_put_user', 'Can run PUT on entity user on action user'), ('user_patch_user', 'Can run PATCH on entity user on action user'), ('user_delete_user', 'Can run DELETE on entity user on action user')],
                'managed': False,
                'default_permissions': [],
            },
        ),
    ]
