# Generated by Django 4.0.7 on 2022-08-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_coreuserpermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreUserPermissionsPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('user_get_user-permission', 'Can run GET on entity user and action user-permission'), ('user_options_user-permission', 'Can run OPTIONS on entity user on action user-permission'), ('user_head_user-permission', 'Can run HEAD on entity user on action user-permission'), ('user_post_user-permission', 'Can run POST on entity user on action user-permission'), ('user_put_user-permission', 'Can run PUT on entity user on action user-permission'), ('user_patch_user-permission', 'Can run PATCH on entity user on action user-permission'), ('user_delete_user-permission', 'Can run DELETE on entity user on action user-permission')],
                'managed': False,
                'default_permissions': [],
            },
        ),
    ]
