# Generated by Django 4.0.7 on 2022-09-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_coreuserpermissionspermissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant_user',
            options={'permissions': [('tenant_get_tenant-user', 'Can run GET on entity tenant and action tenant-user'), ('tenant_options_tenant-user', 'Can run OPTIONS on entity tenant on action tenant-user'), ('tenant_head_tenant-user', 'Can run HEAD on entity tenant on action tenant-user'), ('tenant_post_tenant-user', 'Can run POST on entity tenant on action tenant-user'), ('tenant_put_tenant-user', 'Can run PUT on entity tenant on action tenant-user'), ('tenant_patch_tenant-user', 'Can run PATCH on entity tenant on action tenant-user'), ('tenant_delete_tenant-user', 'Can run DELETE on entity tenant on action tenant-user')]},
        ),
    ]
