# Generated by Django 4.1.9 on 2023-06-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_tenant_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coreuserpermissionspermissions',
            options={'default_permissions': [], 'managed': False, 'permissions': [('user_get_user_permission', 'Can run GET on entity user and action user_permission'), ('user_options_user_permission', 'Can run OPTIONS on entity user on action user_permission'), ('user_head_user_permission', 'Can run HEAD on entity user on action user_permission'), ('user_post_user_permission', 'Can run POST on entity user on action user_permission'), ('user_put_user_permission', 'Can run PUT on entity user on action user_permission'), ('user_patch_user_permission', 'Can run PATCH on entity user on action user_permission'), ('user_delete_user_permission', 'Can run DELETE on entity user on action user_permission')]},
        ),
    ]
