name: Run Tests

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'main'
      - 'release/*'
  pull_request:
    branches:
      - 'main'
      - 'release/*'

jobs:
  consumer-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build consumer_gateway
        run: |
          ls -la
          export BUILD_NF_COMPOSE_DOCKER_TAG=$(bash version.sh)
          cd consumer_gateway
          ARGS='--no-cache' exec bash build_production.sh

  skipper-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build skipper_proxy
        run: |
          ls -la
          export BUILD_NF_COMPOSE_DOCKER_TAG=$(bash version.sh)
          cd skipper_proxy
          ARGS='--no-cache' exec bash build_production.sh

  skipper:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 

      - name: Print environment variables
        run: |
          printenv

      # build this here (without pushing, so the integration tests work)      
      - name: Build skipper_proxy
        run: |
          ls -la
          export BUILD_NF_COMPOSE_DOCKER_TAG=$(bash version.sh)
          cd skipper_proxy
          ARGS='--no-cache' exec bash build_production.sh

      - name: Setup Devenv
        run: |
          bash setup_devenv.sh

      - name: "Run Setup for CI"
        run: |
          cd skipper
          exec python3 build.py setup

      - name: "Run Skipper Tests"
        run: |
          export SKIPPER_DOCKER_IMAGE="ghcr.io/neuroforgede/nfcompose-skipper:ci"
          # skipper_proxy is still in the default place, but we dont push it in this pipeline
          export SKIPPER_PROXY_DOCKER_IMAGE="ghcr.io/neuroforgede/nfcompose-skipper-proxy:ci"

          cd skipper
          exec python3 build.py \
            build \
            --imageName ghcr.io/neuroforgede/nfcompose-skipper \
            --buildBase \
            --skipPush

      - name: "Run client Tests"
        run: |
          export NFCOMPOSE_SETUP_SKIP_PULL="yes"
          export COMPOSE_PROJECT_NAME="ci_test_unit_tests"
          export SKIPPER_DOCKER_IMAGE="ghcr.io/neuroforgede/nfcompose-skipper:ci"
          # skipper_proxy is still in the default place, but we dont push it in this pipeline
          export SKIPPER_PROXY_DOCKER_IMAGE="ghcr.io/neuroforgede/nfcompose-skipper-proxy:ci"

          cd client
          bash ci_test.sh || exit 1

      - name: "Build client source release"
        run: |
          cd client
          python3 -m venv venv
          source venv/bin/activate
          (bash install_dev_dependencies.sh && python3 setup.py sdist) || exit 1